// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs.proto

package clientStreamingCA;

public interface CRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * request from client side
   *the client will send this message more than once to the server
   * </pre>
   *
   * <code>string course = 1;</code>
   */
  java.lang.String getCourse();
  /**
   * <pre>
   * request from client side
   *the client will send this message more than once to the server
   * </pre>
   *
   * <code>string course = 1;</code>
   */
  com.google.protobuf.ByteString
      getCourseBytes();
}
