// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs.proto

package clientStreamingCA;

public interface CResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * request from the server side
   * the server will send just one message once
   * </pre>
   *
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <pre>
   * request from the server side
   * the server will send just one message once
   * </pre>
   *
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
