// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs.proto

package clientStreamingCA;

public final class Cs {
  private Cs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010cs.proto\"\032\n\010CRequest\022\016\n\006course\030\001 \001(\t\"!" +
      "\n\tCResponse\022\024\n\014confirmation\030\001 \001(\t21\n\nAsk" +
      "ForCert\022#\n\006DoCert\022\t.CRequest\032\n.CResponse" +
      "\"\000(\001B\025\n\021clientStreamingCAP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CRequest_descriptor,
        new java.lang.String[] { "Course", });
    internal_static_CResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
